name: CI - Build & Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake and dependencies
        run: sudo apt-get install -y cmake ninja-build g++

      - name: Configure CMake
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug

      - name: Build tests
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
